repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: mixed-line-ending
        args: [--fix=lf]
    -   id: detect-private-key

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v16.0.6'
    hooks:
    -   id: clang-format
        types_or: [c++, c, cuda, cpp, csharp, java, javascript, objective-c, proto]
        args: [--style=file, -i, --Werror]

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3
        args: [--line-length=100, --safe]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: [--profile=black, --filter-files]

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-black, flake8-isort]
        args: [--max-line-length=100, --ignore=E203,W503]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-python-dateutil, types-pyyaml]
        args: [--strict, --ignore-missing-imports, --implicit-optional, --disallow-untyped-defs]
        exclude: ^tests/

-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
    -   id: codespell
        args: [--write-changes, --ignore-words-list="ba,fo,nd,te"]
        exclude: ^(docs|third_party|cmake|build|vcpkg|.git)/
