title: AI-First TextEditor
description: Documentation for AI-First TextEditor
theme: jekyll-theme-cayman
show_downloads: true
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor

# Plugins (optional)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Optional: If you're using a theme, you might want to specify it
# theme: jekyll-theme-minimal

# Optional: If you want to use a custom domain
url: "https://texteditor.chronovyan.com"  # your custom domain
baseurl: "" # leave this as empty string if using a custom domain

# Optional: If you want to use a different markdown processor
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Optional: If you want to enable Google Analytics
google_analytics: UA-XXXXXXXX-X  # Replace with your Google Analytics ID

# Optional: If you want to add a logo or favicon
# logo: /assets/images/logo.png
# favicon: /assets/images/favicon.ico

# Optional: If you want to customize the navigation
# nav:
#   - Home: /index.md
#   - About: /about.md
#   - Blog: /blog/

# Optional: If you want to add social media links
# social:
#   - name: GitHub
#     url: https://github.com/yourusername
#   - name: Twitter
#     url: https://twitter.com/yourusername
