source 'https://rubygems.org'

# This will help ensure the proper Jekyll version is running.
gem 'jekyll', '~> 4.3.2'

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem 'minima', '~> 2.5'

# If you want to use GitHub Pages, uncomment the following line
# gem "github-pages", group: :jekyll_plugins

# Performance-booster for watching directories on Windows
# gem 'wdm', '~> 0.1.0' if Gem.win_platform?

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
