source 'https://rubygems.org'

# Core Jekyll
gem 'jekyll', '~> 4.3.2'

# Theme
gem 'jekyll-theme-cayman', '~> 0.2.0'

# Plugins
group :jekyll_plugins do
  gem 'jekyll-feed', '~> 0.17.0'
  gem 'jekyll-seo-tag', '~> 2.8.0'
end

# For syntax highlighting
gem 'rouge', '~> 4.2.0'

# Performance-booster for watching directories on Windows
gem 'wdm', '~> 0.1.1' if Gem.win_platform?

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo', '~> 2.0'
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
