name: Deploy to GitHub Pages

on:
  # Trigger the workflow on push to the main branch
  push:
    branches: [ "main", "master" ]
  # Allow manual trigger
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'  # Use a recent Ruby version that works with Jekyll
          bundler-cache: true
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          
      - name: Install Jekyll
        run: |
          gem install jekyll bundler
          
      - name: Build with Jekyll
        # Builds the static site to the './_site' directory
        run: |
          cd docs
          # Install the gems specified in Gemfile
          bundle config path vendor/bundle
          bundle install
          # Build the site
          bundle exec jekyll build --baseurl "${{ github.base_ref == 'gh-pages' && '' || '/NexusCore' }}" --destination ../_site
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the entire _site directory
          path: './_site'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
